### ISSUE TITLE
npm tag latest points to upcoming v3-beta

### ISSUE THREAD

**Issue by ofhouse** [ScriptedAlchemy/webpack-external-import#140]
Hi, just noticed that the [`latest`](https://www.npmjs.com/package/webpack-external-import?activeTab=versions) tag on npm currently points to the latest `v3-beta`.

So when I install it using `npm i --save webpack-external-import` this currently gives me `^3.0.0-beta.3` with the readme for the v2.

I think it would make more sense to point the `latest` tag to the v2 until the v3 is out of beta?

**Comment by katiawheeler** [comment]
+1 on this

**Comment by maraisr** [comment]
Thanks for the spot, the `@latest` tag should now point back to 2.2.1 💯 

![image](https://user-images.githubusercontent.com/599459/75288679-8e920a00-5868-11ea-85bb-3675ef7853fe.png)
