### ISSUE TITLE
__webpack_require__ is not defined

### ISSUE THREAD

**Issue by katiawheeler** [ScriptedAlchemy/webpack-external-import#151]
I am attempting to use the `ExternalComponent` per the docs example within a React app. Once I compile it to run locally, I'm getting the following error:

`__webpack_require__ is not defined`

I'm definitely missing something, aren't I?

I have loaded the manifest and can see that it's loading correctly, it's just throwing this error. I'm on Webpack 4.41.2.

**Comment by vedrani** [comment]
I had same issue, did you put `URLImportPlugin` to your host app?
https://github.com/ScriptedAlchemy/webpack-external-import/blob/v2.2.2/manual/webpack/webpackConfigFactory.js#L35

FYI you should try v3 it's based on module federation in webpack 5. It is not production ready, but seems pretty close to it.
https://github.com/ScriptedAlchemy/webpack-external-import/tree/v3-webpack-core

**Comment by ScriptedAlchemy** [comment]
V3 only works on webpack 5, use V2. Otherwise upgrade to the webpack 5 branch this feature is on

**Comment by ScriptedAlchemy** [comment]
https://github.com/mizx/mfe-webpack-demo

**Comment by ScriptedAlchemy** [comment]
V2 is the only one that works with webpack 4, v3 is part of webpack 5 which makes this repository useless. It’s serving only as a place for testing and documentation.
