### ISSUE TITLE
importManifest => external module + dependencies waterfall

### ISSUE THREAD

**Issue by ethersage** [ScriptedAlchemy/webpack-external-import#25]
When you want to import an external module you need to load the manifest first, then you can load any of the modules. There's a waterfall that can add more latency than dynamically importing most code-split bundles:

```
import('http://website1.com/js/theExampleFile.js') // first request
.then(({ExampleModule})=>{ }); // second request

// and what if that module has more dynamic imports?
```

You can preload them, but would be nice to have a utility to do that and handle storing/accessing the paths later so you don't have to pass the manifest around all over your app. Or maybe if the manifest isn't too big it can be bundled into the consumers app so it already knows about the dependencies.

When you consider that there may be a chain of other dependencies the waterfall can get longer. It would be helpful if the manifest could tell you all of the sub-dependencies you're going to need.

**Comment by ScriptedAlchemy** [comment]
solved with importDepenednecies utilites
