### ISSUE TITLE
Broken Integration test

### ISSUE THREAD

**Issue by ScriptedAlchemy** [ScriptedAlchemy/webpack-external-import#31]
@ethersage I'm happy to say that this project is starting to move forward again. It's gone through a major cleanup. 

I've been able to fix all the tests but one. 

I was wondering if you'd have any capacity to provide some guidance on what i need to do :)

```
 ● external script › should console.log

    TypeError: react__WEBPACK_IMPORTED_MODULE_1___default.a.createElement is not a function
```

Id muuuch appreciate it.

**Comment by ethersage** [comment]
I can take a look. Getting back into the swing of things.

**Comment by ScriptedAlchemy** [comment]
Thanks! We must catch up soon! All going well?

**Comment by ethersage** [comment]
@ScriptedAlchemy Going to try to hop on this finally.
