### ISSUE TITLE
using with create-react-app generated webpack config..

### ISSUE THREAD

**Issue by shcarrico** [ScriptedAlchemy/webpack-external-import#41]
Seems to be ignoring the magic comment. I assume there is something stripping it before it can be consumed by your plugin.. ? Any thoughts about where to start looking to make adjustments? 

I have a fork of create-react-app that i'm modifying to generate a consumable react component / MFE that is loaded into a larger app shell. I am trying to keep the subs in the "create-react-app" ecosystem to lower our ongoing maintenance burden for tooling :)

**Comment by shcarrico** [comment]
more details..

module
```jsx
// ...

export default Extension;
// this is a magic comment! do not remove, is required by https://github.com/ScriptedAlchemy/webpack-external-import
/*externalize:Extension*/
```

[webpack.config.js.txt](https://github.com/ScriptedAlchemy/webpack-external-import/files/3659439/webpack.config.js.txt)

**Comment by ScriptedAlchemy** [comment]
Try it now, I made a few modifications. 

I believe it was an issue with how splitChunks was getting merged in
