### ISSUE TITLE
Could you update babel-traverse dependency? As core-js@2 has been deprecated.

### ISSUE THREAD

**Issue by midnight-wonderer** [ScriptedAlchemy/webpack-external-import#47]
Hi there,
Our project depends on `extract-css-chunks-webpack-plugin` and npm warn us with the following warning:

> npm WARN deprecated core-js@2.6.10: core-js@<3.0 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.

The dependency graph is as the following

> extract-css-chunks-webpack-plugin > webpack-external-import > babel-traverse > babel-runtime > core-js

The new version of `babel-traverse` does not depends on `core-js` anymore. So, I guess this is the right place to start updating.

I don't really have a practical issue apart from the warning. Just giving you guys a nudge.

**Comment by midnight-wonderer** [comment]
I don't see it being used anywhere so I can't send a PR.  
I see some attempts at https://github.com/ScriptedAlchemy/webpack-external-import/pull/46 though.

**Comment by ScriptedAlchemy** [comment]
Will do

**Comment by ScriptedAlchemy** [comment]
@midnight-wonderer whats the version that supports? the 7.0 beta? is it stable?

**Comment by midnight-wonderer** [comment]
They change their npm package name.
https://www.npmjs.com/package/@babel/traverse

**Comment by ScriptedAlchemy** [comment]
Ahhhhhhhh! Okay will do
