### ISSUE TITLE
Unable to load nested dependencies

### ISSUE THREAD

**Issue by ppiyush13** [ScriptedAlchemy/webpack-external-import#59]
Well I was playing around with `webpack-external-import` plugin and hit a case where not all the dependencies of external build where imported. I would illustrate further with the example.

Assume I have one child app and a parent app. Child acts like a MFE. Parent pulls child app at runtime and should pull all the missing dependencies from child app.
I was looking at your excellent [medium](https://medium.com/javascript-in-plain-english/micro-frontend-architecture-dynamic-import-chunks-from-another-webpack-bundle-at-runtime-1132d8cb6051?) article and decided to split every node module in child application by using following optimization.splitChunks in webpack configs:

```
splitChunks: {
    chunks: 'all',
    maxInitialRequests: Infinity,
    minSize: 0,
    cacheGroups: {
        vendor: {
            test: /[\\/]node_modules[\\/]/,
            name(module) {
                // get the name. E.g. node_modules/packageName/not/this/part.js
                // or node_modules/packageName
                const packageName = module.context.match(/[\\/]node_modules[\\/](.*?)([\\/]|$)/)[1];
                // npm package names are URL-safe, but some servers don't like @ symbols
                return `npm.${packageName.replace('@', '')}`;
            },
        },
    },
 },
```

Following is the importManifest generated for child app:

```
if(!window.entryManifest) {window.entryManifest = {}}; window.entryManifest["App1Manifest"] = {
  "App1.js": {
    "path": "App1.js",
    "dependencies": [
      {
        "order": 2,
        "name": "react",
        "id": "LDoPTt+kJa",
        "sourceFiles": [
          "npm.react.js"
        ]
      },
      {
        "order": 1,
        "name": "@babel/runtime/helpers/taggedTemplateLiteral",
        "id": "jkkCvB1L1I",
        "sourceFiles": [
          "npm.babel.js"
        ]
      },
      {
        "order": 3,
        "name": "styled-components",
        "id": "QiEJoypLKc",
        "sourceFiles": [
          "npm.styled-components.js"
        ]
      }
    ],
    "isInitial": true
  },
  "main.js": {
    "path": "main.js",
    "dependencies": null,
    "isInitial": true
  },
  "npm.babel.js": {
    "path": "npm.babel.js",
    "dependencies": null,
    "isInitial": true
  },
  "npm.emotion.js": {
    "path": "npm.emotion.js",
    "dependencies": null,
    "isInitial": true
  },
  "npm.is-what.js": {
    "path": "npm.is-what.js",
    "dependencies": null,
    "isInitial": true
  },
  "npm.memoize-one.js": {
    "path": "npm.memoize-one.js",
    "dependencies": null,
    "isInitial": true
  },
  "npm.merge-anything.js": {
    "path": "npm.merge-anything.js",
    "dependencies": null,
    "isInitial": true
  },
  "npm.object-assign.js": {
    "path": "npm.object-assign.js",
    "dependencies": null,
    "isInitial": true
  },
  "npm.process.js": {
    "path": "npm.process.js",
    "dependencies": null,
    "isInitial": true
  },
  "npm.prop-types.js": {
    "path": "npm.prop-types.js",
    "dependencies": null,
    "isInitial": true
  },
  "npm.react.js": {
    "path": "npm.react.js",
    "dependencies": null,
    "isInitial": true
  },
  "npm.react-dom.js": {
    "path": "npm.react-dom.js",
    "dependencies": null,
    "isInitial": true
  },
  "npm.react-is.js": {
    "path": "npm.react-is.js",
    "dependencies": null,
    "isInitial": true
  },
  "npm.scheduler.js": {
    "path": "npm.scheduler.js",
    "dependencies": null,
    "isInitial": true
  },
  "npm.styled-components.js": {
    "path": "npm.styled-components.js",
    "dependencies": null,
    "isInitial": true
  },
  "npm.stylis.js": {
    "path": "npm.stylis.js",
    "dependencies": null,
    "isInitial": true
  },
  "npm.stylis-rule-sheet.js": {
    "path": "npm.stylis-rule-sheet.js",
    "dependencies": null,
    "isInitial": true
  },
  "runtime.js": {
    "path": "runtime.js",
    "dependencies": null,
    "isInitial": true
  },
  "./index.html": {
    "path": "./index.html",
    "dependencies": null,
    "isInitial": null
  }
}
```

So I am using `react` and `styled-components` in child app. Same version of react is present in parent app as well. So no need to pull react from child app. But styled-components is not present in parent. So it goes to import missing dependency from child app as expected.

But it appears that dependencies of `styled-components(like stylis, stylis-rule-sheet)` are not pulled into parent only styled-components was pulled. So parent is not able to resolve `stylis` and `stylis-rule-sheet`. 

And if we observe importManifest above, styled-components are marked with null as dependencies. I think this is what is causing issue.

Am I missing anything here ? 
Are splitting all the npm modules into separate chunks is not expected ?

**Comment by ScriptedAlchemy** [comment]
Ahh thanks for testing this out! If you have time, I’d love you to PR the demo under the manual folder to reflect this issue. I’m currently working on internal module resolution using the native webpack mechanisms. This is by modifying the webpack bootstrap and webpack require methods along with how and what is written to chunks. If I have something to test it against I can make sure to resolve your specific challenges in the next release. 

Nested dependencies has been on the list and should be resolved soon

**Comment by ppiyush13** [comment]
Seems like a good idea. For now I have created example repo for this issue.
https://github.com/ppiyush13/webpack-external-import-example-granular-import

Feel free to add the contents in manual folder. This could be good start to test your fix for this issue. Instructions for the demo are included in repo's readme.md

**Comment by ScriptedAlchemy** [comment]
#63 is open for review if you'd care to have a look

**Comment by ScriptedAlchemy** [comment]
its far better at tracking dependencies and loading them. V1 was primitive in this manner, V2 beta - when released to npm as a beta - solved a ton
