### ISSUE TITLE
GPL License 

### ISSUE THREAD

**Issue by hamsterbacke23** [ScriptedAlchemy/webpack-external-import#65]
Hello, 
I wanted to ask you what's the reason for the GPL license. 

We have a problem right now because we bundle nuxt in our commercial app and only this dependency has GPL. All parent dependencies of webpack-external-import have MIT. As sublicensing is not allowed, we would need to change our license of our whole app to GPL only because of this single dependency. 

 nuxt@2.11.0
  └─┬ @nuxt/webpack@2.11.0
    └─┬ extract-css-chunks-webpack-plugin@4.7.1
      └── webpack-external-import@0.3.0-beta.0 

Is there are reason for this or would it be possible to change the license, e.g. to MIT or something?

**Comment by ScriptedAlchemy** [comment]
I’ll publish a special tag with loser license agreements. 

In general, I’m looking at using a more restrictive license for this tool. But I can publish a MIT copy to extract css chunks. I’ve got a performance upgrade about to release on extract css. So I’ll include it in that

**Comment by hamsterbacke23** [comment]
Interesting! I bet a MIT dependency of external-import for extract-css-chunks would make a lot of people sleep better over not having to worry about their license-checker and not having to make sure this dependency doesn't end up in the production build.
Cheers!

**Comment by ScriptedAlchemy** [comment]
@hamsterbacke23 extract-css-chunks-webpack-plugin@4.7.2-mit

**Comment by ScriptedAlchemy** [comment]
created a MIT version till i release V2 with an mit version as well
