### ISSUE TITLE
Unable to run __webpack_require() within a create-react-app

### ISSUE THREAD

**Issue by netusco** [ScriptedAlchemy/webpack-external-import#87]
I'm trying to apply this plugin to import/export components between 2 different create-react-apps.
I can load the importManifest and even get the url after resolving importDependenciesOf().
The error happens if I try to import() dynamically and __webpack_require() the component or if I use the ExternalComponent. It actually fails also on __webpack_require() within react.js file https://github.com/ScriptedAlchemy/webpack-external-import/blob/master/src/react.js#L46

I'm not sure if this is related to a missconfiguration of webpack or a webpack plugin that is interfering..

**Comment by ScriptedAlchemy** [comment]
Ive just released v2 which loads most of this internally. Give that a try and then if you can replicate the issue in a demo repo - send it over
